### ISSUE TITLE
DAP: Google Symptoms Signal

### ISSUE THREAD

**Issue by bweaver-work** [cmu-delphi/covidcast-modeling#16]
NOTE: This is a test issue to track a DAP using github issues and project boards

---
Stakeholder: @ryantibs  
Advisor: @drnigam
Analyst: @nmdefries @jingjtang @huisaddison 
---

Description & Deliverables (link or text):
[DAP Projects Doc: Google Symptom Signals](https://docs.google.com/document/d/1a47TPdhvGPXWkD6hrX_16hhmcTaIMVUxIs57UZ5MOh4/edit#heading=h.lrztorn7a1cm)

**Comment by capnrefsmmat** [comment]
Our CDC contact has pointed us to several sets of symptom clinical criteria here: https://wwwn.cdc.gov/nndss/conditions/coronavirus-disease-2019-covid-19/case-definition/2020/08/05/
